### Install `dtmapi`

In [ ]:
pip install dtmapi

### Import `dtmapi`

In [ ]:
from dtmapi import DTMApi

api = DTMApi(subscription_key="YOUR-API-KEY-HERE")

### Get All Countries

In [11]:
# Get all countries for which DTM data is publicly available through the API.
all_country_list = api.get_all_countries()
all_country_list.head()

                         admin0Name admin0Pcode
0                       Afghanistan         AFG
1               Antigua and Barbuda         ATG
2                     Bahamas (the)         BHS
3                             Benin         BEN
4  Bolivia (Plurinational State of)         BOL

### Get All Operations

In [12]:
# Get all operations for which DTM data is publicly available through the API.
all_operation_list = api.get_all_operations()
all_operation_list.head()

,operation,operationStatus,admin0Name,admin0Pcode
0,Aceh earthquake,Inactive,Indonesia,IDN
1,Armed Clashes in Sudan,Active,Sudan,SDN
2,Armed Clashes in Sudan (Monthly),Active,Sudan,SDN
3,Armed Clashes in Sudan (Overview),Active,Sudan,SDN
4,Arrivals in Armenia,Inactive,Republic of Armenia,ARM

### Get IDP Admin 0 Data

In [13]:
# Get IDP Admin 0 Data for Ethiopia from Round 1 to Round 10
idp_admin0_data = api.get_idp_admin0_data(CountryName='Ethiopia', FromRoundNumber=1, ToRoundNumber=10)
idp_admin0_data.head()

,operation,admin0Name,admin0Pcode,numPresentIdpInd,reportingDate,yearReportingDate,monthReportingDate,roundNumber,displacementReason,numberMales,numberFemales,idpOriginAdmin1Name,idpOriginAdmin1Pcode,assessmentType
0,Countrywide monitoring,Ethiopia,ETH,7823,2017-12-31T00:00:00,2017,12,8,Conflict,4088,3735,Afar,ET02,SA
1,Countrywide monitoring,Ethiopia,ETH,21668,2017-12-31T00:00:00,2017,12,8,Conflict,11490,10178,Amhara,ET03,SA
2,Countrywide monitoring,Ethiopia,ETH,15420,2017-12-31T00:00:00,2017,12,8,Conflict,7046,8374,Gambela,ET12,SA
3,Countrywide monitoring,Ethiopia,ETH,772924,2017-12-31T00:00:00,2017,12,8,Conflict,375655,397269,Oromia,ET04,SA
4,Countrywide monitoring,Ethiopia,ETH,308300,2017-12-31T00:00:00,2017,12,8,Conflict,152469,155831,Somali,ET05,SA

### Get IDP Admin 1 Data

In [14]:
# Get IDP Admin 1 Data for Sudan from reporting date 2020-01-01 to 2024-08-15
idp_admin1_data = api.get_idp_admin1_data(CountryName='Sudan', Admin1Name="Blue Nile", FromReportingDate='2020-01-01', ToReportingDate='2024-08-15')
idp_admin1_data.head()

,id,operation,admin0Name,admin0Pcode,admin1Name,admin1Pcode,numPresentIdpInd,reportingDate,yearReportingDate,monthReportingDate,roundNumber,displacementReason,numberMales,numberFemales,idpOriginAdmin1Name,idpOriginAdmin1Pcode,assessmentType
0,1201966,Darfur conflict,Sudan,SDN,Blue Nile,SD08,81693,2021-03-30T00:00:00,2021,3,2,Conflict,0,0,Blue Nile,SD08,BA
1,1201967,Darfur conflict,Sudan,SDN,Blue Nile,SD08,130958,2021-12-31T00:00:00,2021,12,3,Conflict; Natural Disaster,0,0,Blue Nile,SD08,BA
2,1201968,Darfur conflict,Sudan,SDN,Blue Nile,SD08,151156,2022-01-31T00:00:00,2022,1,4,Conflict,0,0,Not avialable,Not avialable,BA
3,1201969,Darfur conflict,Sudan,SDN,Blue Nile,SD08,152656,2022-03-30T00:00:00,2022,3,5,Conflict,0,0,Blue Nile,SD08,BA
4,1181325,Armed Clashes in Sudan,Sudan,SDN,Blue Nile,SD08,260,2023-04-28T00:00:00,2023,4,2,Conflict,0,0,West Darfur,SD04,BA

### Get IDP Admin 2 Data

In [15]:
# Get IDP Admin 2 Data for Lebanon
idp_admin2_data = api.get_idp_admin2_data(Operation="Displacement due to conflict", CountryName='Lebanon')
idp_admin2_data.head()

,id,operation,admin0Name,admin0Pcode,admin1Name,admin1Pcode,admin2Name,admin2Pcode,numPresentIdpInd,reportingDate,yearReportingDate,monthReportingDate,roundNumber,displacementReason,numberMales,numberFemales,idpOriginAdmin1Name,idpOriginAdmin1Pcode,assessmentType
0,4723802,Displacement due to conflict,Lebanon,LBN,Mount Lebanon,LB3,Baabda,LB32,10,2023-10-15T00:00:00,2023,10,2,Conflict,0,0,Mount Lebanon,LB3,BA
1,4728578,Displacement due to conflict,Lebanon,LBN,Beirut,LB1,Beirut,LB11,25,2023-10-15T00:00:00,2023,10,1,Conflict,0,0,Mount Lebanon,LB3,BA
2,4729593,Displacement due to conflict,Lebanon,LBN,South,LB6,Saida,LB61,10,2023-10-15T00:00:00,2023,10,2,Conflict,0,0,Not avialable,Not avialable,BA
3,4731043,Displacement due to conflict,Lebanon,LBN,Baalbek-El Hermel,LB8,Baalbek,LB21,9,2023-10-15T00:00:00,2023,10,1,Conflict,0,0,El Nabatieh,LB4,BA
4,4733389,Displacement due to conflict,Lebanon,LBN,Mount Lebanon,LB3,Baabda,LB32,49,2023-10-15T00:00:00,2023,10,2,Conflict,0,0,South,LB6,BA